### ISSUE TITLE
catch all exceptions is not a viable solution

### ISSUE THREAD

**Issue by flyingfrog81** [ska-telescope/lmc-base-classes#105]
https://github.com/ska-telescope/lmc-base-classes/blob/41579b8b872fc5c046b1a02fe069f048f59c08b1/skabase/SKABaseDevice/SKABaseDevice.py#L64

I don't think this is an appropriate solution. 
1) Only the relevant execption should be caught. 
2) It would be better to have a `try...except` only around logging initialization
3) The except should provide a fallback solution, a print statement is not solving the issue. Ideally the fallback should be to initiate logging on a file instead of using rsyslog.

**Comment by adityadangeska** [comment]
Added exception handling wherever applicable. PR#113 addresses this.
