### ISSUE TITLE
Implement state machines for the SKABaseDevice and SKASubarray

### ISSUE THREAD

**Issue by kmadisa** [ska-telescope/lmc-base-classes#52]
@ajoubertza  suggested that we make use of the  [state machine library](https://github.com/pytransitions/transitions) to implement the state machines in the [PR#46](https://github.com/ska-sa/levpro/pull/46).
Currently we have the rules for some commands specified in the `_is_command_allowed` helper method and the more command handlers we implement, the more cumbersome it will become.

**Comment by kmadisa** [comment]
Seems to be resolved by https://gitlab.com/ska-telescope/lmc-base-classes/-/merge_requests/18.

**Comment by ajoubertza** [comment]
Agree
