### ISSUE TITLE
Why separate packages

### ISSUE THREAD

**Issue by flyingfrog81** [ska-telescope/lmc-base-classes#80]
Having a quick look at the content I see every class is installed as a separate python package. What is the rationale behind this choice?

**Comment by adityadangeska** [comment]
This is just to keep this thread up-to-date:
The lmc base classes are repackaged and all the base classes are now packaged in single python package. The directory structure is modified as part of repackaging and some of the files are removed as well.
The discussion related to modifications in POGO is still relevant and open though.

**Comment by flyingfrog81** [comment]
Thanks @adityadangeska , I think we can now close this thread.
We now have a feature in our program backlog about modifying POGO and relevant information should be added there. I think we now realize the importance of keeping the xmi files relevant so I'd be in great favour of improving POGO to support python package structure. 
You can see the feature at: https://jira.skatelescope.org/browse/SP-89
